### PR TITLE
HUB - Update HUBG to v0.90

### PR DESCRIPTION
**Pull request by ducasp**
@israelferrazaraujo was kind enough to update HUBG to dynamically allocate memory entries which extends the capability of packages in a given category (i.e. games now has 132 packages!) for more than 70, depending only on how much space of description each package uses. Now it is able to fully list the games category and you can retrieve any of the 132 entries there...

### CODE REVIEW

**Comment by ducasp** [comment]
Hi @fr3nd , whenever you can please review this update request, there is a new version of HUBG overcoming the 70 packages per category limitation of previous versions, which is good due to the huuuuge games section :) Not sure what are the limits now, as it is kind of dynamic (great idea by Israel, not requiring mapper or extra ram or disk access) but it is enough to list all 132 games currently listed :) Thanks and hope all is fine with you!

**Review by fr3nd — APPROVED** [review]
Really nice addition! Thank you!! I'll release it right away. :)

**Comment by israelferrazaraujo** [comment]
Hey fellows,

I'm so glad that you guys accepted the HUBG update. Thank you!

But I must say that the `HUBG.COM` file is not in the HUB package.

image

**Comment by fr3nd** [comment]
Hey @israelferrazaraujo 
You're right. Thank you for reporting it. There was an error in the package file. I've fixed it, and it should be appearing now.
Best

**Pull request merged**
